#!/usr/bin/env bash
# bootstrap-peer.sh — set up VM2 as the test peer junto-memory.
#
# Run on a freshly-provisioned Ubuntu Server 24.04 VM AFTER VM1 has run
# bootstrap-primary.sh and you've copied its peer-credentials.txt over.
#
# Required env (must be exported or passed inline):
#   JUNTO_SYNC_PRIMARY_URL    e.g. http://test-primary.<tailnet>.ts.net:8080/mcp
#   JUNTO_SYNC_PRIMARY_KEY    smk_... from VM1's peer-credentials.txt
# Optional:
#   ORIGIN_SERVER_ID          default peer-xavier-1
#   REPO_DIR                  default $(pwd)
#
# What it does:
#   1. Verifies docker + docker compose + git + openssl + curl.
#   2. Verifies the primary URL is actually reachable (fail loud here, not
#      later inside the sync-engine container).
#   3. Generates Mongo keyfile.
#   4. Writes initial .env with LOCAL_KEY=placeholder (sync-engine will not
#      be started yet).
#   5. Brings up chromadb + mongodb + mcp-server.
#   6. Runs rs.initiate() on mongodb if rs0 isn't yet initialized. Required
#      on fresh installs: the mongo:7.0 image's entrypoint does NOT auto-
#      initiate the replica set, and writes will fail with "No primary
#      exists" until this runs (even though docker's healthcheck passes).
#   7. Waits for /health.
#   8. Issues this peer's admin API key (JUNTO_SYNC_LOCAL_KEY).
#   9. Rewrites .env with the real LOCAL_KEY and starts sync-engine.
#  10. Tails sync-engine logs briefly so you see pull/push loop start.

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(pwd)}"
ORIGIN_SERVER_ID="${ORIGIN_SERVER_ID:-peer-xavier-1}"

: "${JUNTO_SYNC_PRIMARY_URL:?must be set (see peer-credentials.txt from VM1)}"
: "${JUNTO_SYNC_PRIMARY_KEY:?must be set (see peer-credentials.txt from VM1)}"

log() { printf '[bootstrap-peer] %s\n' "$*" >&2; }

step1_prereqs() {
  log "step 1/10: checking prerequisites"
  command -v docker >/dev/null || { log "docker not found"; exit 1; }
  docker compose version >/dev/null || { log "docker compose v2 not found"; exit 1; }
  command -v git >/dev/null || { log "git not found"; exit 1; }
  command -v openssl >/dev/null || { log "openssl not found"; exit 1; }
  command -v curl >/dev/null || { log "curl not found"; exit 1; }
  [[ -f "$REPO_DIR/docker-compose.peer.yml" ]] || {
    log "docker-compose.peer.yml not found in $REPO_DIR"; exit 1
  }
}

step2_primary_reachable() {
  log "step 2/10: verifying primary URL reachable"
  local health_url="${JUNTO_SYNC_PRIMARY_URL%/mcp}/health"
  if curl -fsS --max-time 10 "$health_url" >/dev/null 2>&1; then
    log "  primary /health OK at $health_url"
  else
    log "  WARNING: $health_url did not respond. Sync-engine will fail until reachable."
    log "  Continuing anyway — useful if you intend to test offline-start behavior."
  fi
}

step3_keyfile() {
  log "step 3/10: ensuring Mongo keyfile"
  mkdir -p "$REPO_DIR/secrets"
  if [[ ! -s "$REPO_DIR/secrets/mongo-keyfile" ]]; then
    openssl rand -base64 756 > "$REPO_DIR/secrets/mongo-keyfile"
    chmod 400 "$REPO_DIR/secrets/mongo-keyfile"
    sudo chown 999:999 "$REPO_DIR/secrets/mongo-keyfile"
    log "  generated new keyfile"
  else
    log "  already present"
  fi
}

step4_env_initial() {
  log "step 4/10: writing initial .env (LOCAL_KEY=placeholder)"
  if [[ -f "$REPO_DIR/.env" ]]; then
    log "  .env exists — leaving untouched (delete to re-generate)"
    return
  fi
  local mongo_pw
  mongo_pw="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  cat > "$REPO_DIR/.env" <<EOF
# Generated by bootstrap-peer.sh on $(date -Iseconds)
MONGO_USER=mcp_orch
MONGO_PASSWORD=$mongo_pw
MONGO_DB=mcp_orchestrator

ORIGIN_SERVER_ID=$ORIGIN_SERVER_ID

JUNTO_SYNC_PRIMARY_URL=$JUNTO_SYNC_PRIMARY_URL
JUNTO_SYNC_PRIMARY_KEY=$JUNTO_SYNC_PRIMARY_KEY
# Filled in by step 7.
JUNTO_SYNC_LOCAL_KEY=placeholder
EOF
  chmod 600 "$REPO_DIR/.env"
  log "  wrote $REPO_DIR/.env (mode 600)"
}

step5_compose_up() {
  log "step 5/10: bringing up chromadb + mongodb + mcp-server"
  cd "$REPO_DIR"
  docker compose -f docker-compose.peer.yml up -d --build chromadb mongodb mcp-server
}

# Idempotently initiate the rs0 single-node replica set. See identical step
# in bootstrap-primary.sh for the full why — the short version: mongo:7.0's
# entrypoint doesn't call rs.initiate(), docker's healthcheck passes anyway
# (it uses directConnection=true), but writes fail with "No primary exists".
step6_initiate_rs() {
  log "step 6/10: ensuring rs0 replica set is initiated"
  # shellcheck disable=SC1091
  set -a; source "$REPO_DIR/.env"; set +a
  local primary_host="${MONGO_RS_HOST:-mongodb}"
  local n=0
  until docker exec junto-peer-mongodb mongosh --quiet --norc \
    "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/?directConnection=true&authSource=admin" \
    --eval "
      try {
        const s = rs.status();
        if (s.ok && s.members && s.members.some(m => m.stateStr === 'PRIMARY')) {
          print('rs0 already initialized with primary');
          quit(0);
        }
      } catch (e) {
        if (e.codeName !== 'NotYetInitialized' && e.code !== 94) {
          print('rs.status failed: ' + e.message);
          quit(1);
        }
        const r = rs.initiate({_id: 'rs0', members: [{_id: 0, host: '${primary_host}:27017'}]});
        if (!r.ok) { print('rs.initiate failed: ' + JSON.stringify(r)); quit(1); }
        print('rs0 initiated');
      }
      for (let i = 0; i < 30; i++) {
        try {
          if (db.hello().isWritablePrimary) { print('primary elected after ' + i + 's'); quit(0); }
        } catch (e) {}
        sleep(1000);
      }
      print('primary never elected'); quit(1);
    " >/dev/null 2>&1; do
    n=$((n+1))
    if (( n > 12 )); then
      log "  rs.initiate never succeeded — check 'docker logs junto-peer-mongodb'"
      exit 1
    fi
    sleep 5
  done
  log "  rs0 ready"
}

step7_wait_health() {
  log "step 7/10: waiting for /health"
  local n=0
  until curl -fsS http://localhost:8080/health >/dev/null 2>&1; do
    n=$((n+1))
    if (( n > 60 )); then
      log "  /health never came up — check 'docker logs junto-peer-mcp-server'"
      exit 1
    fi
    sleep 2
  done
  log "  /health OK after ~$((n*2))s"
}

step8_issue_local_key() {
  log "step 8/10: issuing this peer's admin API key"
  # Idempotency guard: if .env already has a non-placeholder LOCAL_KEY, a
  # prior run already minted one. The raw key can't be recovered from Mongo,
  # so creating a same-named replacement would just hit api_keys.name's
  # unique index. Reuse whatever's already in .env.
  local current_key
  current_key="$(awk -F= '/^JUNTO_SYNC_LOCAL_KEY=/{sub(/^JUNTO_SYNC_LOCAL_KEY=/,""); print; exit}' "$REPO_DIR/.env" 2>/dev/null)"
  if [[ -n "$current_key" && "$current_key" != "placeholder" ]]; then
    log "  .env already has a real JUNTO_SYNC_LOCAL_KEY — leaving untouched."
    log "  Delete .env (and revoke the old key in mongo) to regenerate."
    return
  fi
  local raw
  # `get_mongo()` prints "Connected to MongoDB at ..." to stdout on first
  # init, which would otherwise end up captured by $(...) as part of $raw.
  # Filter to lines that look like the smk_-prefixed key from auth.py:67.
  raw="$(docker exec junto-peer-mcp-server python -c "
from shared_memory.auth import create_api_key
raw, _ = create_api_key(name='sync-engine-local', role='admin', created_by='bootstrap-peer.sh')
print(raw)
" | awk '/^smk_/{print; exit}')"
  [[ -n "$raw" ]] || { log "  key creation returned empty"; exit 1; }
  # Replace the placeholder line in .env.
  sed -i "s|^JUNTO_SYNC_LOCAL_KEY=.*|JUNTO_SYNC_LOCAL_KEY=$raw|" "$REPO_DIR/.env"
  log "  LOCAL_KEY set in .env"
}

step9_start_sync_engine() {
  log "step 9/10: starting sync-engine"
  cd "$REPO_DIR"
  docker compose -f docker-compose.peer.yml up -d --force-recreate sync-engine
}

step10_tail_logs() {
  log "step 10/10: brief log tail (Ctrl-C is safe; sync-engine keeps running)"
  log "  expect: 'starting pull loop' + 'starting push loop' within ~10s"
  # 15s tail then exit, so the script terminates cleanly in non-interactive runs.
  timeout 15 docker logs -f junto-peer-sync-engine 2>&1 || true
  log ""
  log "DONE."
  log "  Peer ORIGIN_SERVER_ID: $ORIGIN_SERVER_ID"
  log "  Peer MCP endpoint:     http://$(ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | head -1):8080/mcp"
  log "  Sync engine:           docker logs -f junto-peer-sync-engine"
}

step1_prereqs
step2_primary_reachable
step3_keyfile
step4_env_initial
step5_compose_up
step6_initiate_rs
step7_wait_health
step8_issue_local_key
step9_start_sync_engine
step10_tail_logs
