#!/usr/bin/env bash
# bootstrap-primary.sh — set up VM1 as the test-primary junto-memory.
#
# Run on a freshly-provisioned Ubuntu Server 24.04 VM. Idempotent: re-running
# only re-creates what's missing.
#
# What it does:
#   1. Verifies docker + docker compose + git are present (does not install
#      them; see docs/phase2-acceptance.md for the prereq step).
#   2. Generates Mongo keyfile (secrets/mongo-keyfile, 400, owned by 999:999).
#   3. Writes .env with random Mongo password + ORIGIN_SERVER_ID=test-primary-1
#      and placeholder JUNTO_SYNC_* values (sync-engine is NOT started here).
#   4. Brings up chromadb + mongodb + mcp-server (skips sync-engine).
#   5. Waits for /health, then issues an admin API key for the peer to use.
#   6. Writes the peer's-view-of-primary key to ./peer-credentials.txt.
#
# Exits non-zero on any step's failure. Output is meant to be paste-back-able.

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(pwd)}"
ORIGIN_SERVER_ID="${ORIGIN_SERVER_ID:-test-primary-1}"
PRIMARY_KEY_NAME="${PRIMARY_KEY_NAME:-peer-xavier-1-sync}"
CREDS_OUT="${CREDS_OUT:-$REPO_DIR/peer-credentials.txt}"

log() { printf '[bootstrap-primary] %s\n' "$*" >&2; }

step1_prereqs() {
  log "step 1/6: checking prerequisites"
  command -v docker >/dev/null || { log "docker not found — install first"; exit 1; }
  docker compose version >/dev/null || { log "docker compose v2 not found"; exit 1; }
  command -v git >/dev/null || { log "git not found"; exit 1; }
  command -v openssl >/dev/null || { log "openssl not found"; exit 1; }
  command -v curl >/dev/null || { log "curl not found"; exit 1; }
  [[ -f "$REPO_DIR/docker-compose.peer.yml" ]] || {
    log "docker-compose.peer.yml not found in $REPO_DIR — wrong CWD?"; exit 1
  }
}

step2_keyfile() {
  log "step 2/6: ensuring Mongo keyfile"
  mkdir -p "$REPO_DIR/secrets"
  if [[ ! -s "$REPO_DIR/secrets/mongo-keyfile" ]]; then
    openssl rand -base64 756 > "$REPO_DIR/secrets/mongo-keyfile"
    chmod 400 "$REPO_DIR/secrets/mongo-keyfile"
    sudo chown 999:999 "$REPO_DIR/secrets/mongo-keyfile"
    log "  generated new keyfile"
  else
    log "  already present"
  fi
}

step3_env() {
  log "step 3/6: writing .env"
  if [[ -f "$REPO_DIR/.env" ]]; then
    log "  .env exists — leaving untouched (delete to re-generate)"
    return
  fi
  local mongo_pw
  mongo_pw="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  cat > "$REPO_DIR/.env" <<EOF
# Generated by bootstrap-primary.sh on $(date -Iseconds)
MONGO_USER=mcp_orch
MONGO_PASSWORD=$mongo_pw
MONGO_DB=mcp_orchestrator

ORIGIN_SERVER_ID=$ORIGIN_SERVER_ID

# sync-engine vars: not used (sync-engine isn't started on the test-primary).
# Set to placeholders so docker-compose env parsing doesn't fail if anyone
# ever runs \`docker compose -f docker-compose.peer.yml up sync-engine\` here.
JUNTO_SYNC_PRIMARY_URL=http://placeholder/mcp
JUNTO_SYNC_PRIMARY_KEY=placeholder
JUNTO_SYNC_LOCAL_KEY=placeholder
EOF
  chmod 600 "$REPO_DIR/.env"
  log "  wrote $REPO_DIR/.env (mode 600)"
}

step4_compose_up() {
  log "step 4/6: bringing up chromadb + mongodb + mcp-server"
  cd "$REPO_DIR"
  docker compose -f docker-compose.peer.yml up -d --build chromadb mongodb mcp-server
}

step5_wait_health() {
  log "step 5/6: waiting for /health"
  local n=0
  until curl -fsS http://localhost:8080/health >/dev/null 2>&1; do
    n=$((n+1))
    if (( n > 60 )); then
      log "  /health never came up — check 'docker logs junto-peer-mcp-server'"
      exit 1
    fi
    sleep 2
  done
  log "  /health OK after ~$((n*2))s"
}

step6_issue_key() {
  log "step 6/6: issuing admin API key for peer to use"
  local raw
  raw="$(docker exec junto-peer-mcp-server python -c "
from shared_memory.auth import create_api_key
raw, _ = create_api_key(name='$PRIMARY_KEY_NAME', role='admin', created_by='bootstrap-primary.sh')
print(raw)
")"
  [[ -n "$raw" ]] || { log "  key creation returned empty — investigate"; exit 1; }

  local primary_ip
  primary_ip="$(ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | head -1)"

  cat > "$CREDS_OUT" <<EOF
# Generated by bootstrap-primary.sh on $(date -Iseconds)
# Hand these to bootstrap-peer.sh on VM2.
#
# After Tailscale is up on this VM, replace JUNTO_SYNC_PRIMARY_URL's host
# with this VM's tailnet name/IP (e.g., http://primary.<tailnet>.ts.net:8080/mcp).
JUNTO_SYNC_PRIMARY_URL=http://$primary_ip:8080/mcp
JUNTO_SYNC_PRIMARY_KEY=$raw
ORIGIN_SERVER_ID_REMOTE=$ORIGIN_SERVER_ID
EOF
  chmod 600 "$CREDS_OUT"
  log "  wrote $CREDS_OUT (mode 600)"
  log ""
  log "DONE. Hand $CREDS_OUT to VM2 (peer)."
  log "Current LAN IP: $primary_ip"
  log "Once Tailscale is up, swap the host in JUNTO_SYNC_PRIMARY_URL for the tailnet address."
}

step1_prereqs
step2_keyfile
step3_env
step4_compose_up
step5_wait_health
step6_issue_key
