#!/usr/bin/env bash
# bootstrap-primary.sh — set up VM1 as the test-primary junto-memory.
#
# Run on a freshly-provisioned Ubuntu Server 24.04 VM. Idempotent: re-running
# only re-creates what's missing.
#
# What it does:
#   1. Verifies docker + docker compose + git are present (does not install
#      them; see docs/phase2-acceptance.md for the prereq step).
#   2. Generates Mongo keyfile (secrets/mongo-keyfile, 400, owned by 999:999).
#   3. Writes .env with random Mongo password + ORIGIN_SERVER_ID=test-primary-1
#      and placeholder JUNTO_SYNC_* values (sync-engine is NOT started here).
#   4. Brings up chromadb + mongodb + mcp-server (skips sync-engine).
#   5. Runs rs.initiate() on mongodb if rs0 isn't yet initialized. The
#      mongo:7.0 image's entrypoint does NOT auto-initiate the replica set —
#      writes will fail with "No primary exists" until this runs.
#   6. Waits for /health, then issues an admin API key for the peer to use.
#   7. Writes the peer's-view-of-primary key to ./peer-credentials.txt.
#
# Exits non-zero on any step's failure. Output is meant to be paste-back-able.

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(pwd)}"
ORIGIN_SERVER_ID="${ORIGIN_SERVER_ID:-test-primary-1}"
PRIMARY_KEY_NAME="${PRIMARY_KEY_NAME:-peer-xavier-1-sync}"
CREDS_OUT="${CREDS_OUT:-$REPO_DIR/peer-credentials.txt}"

log() { printf '[bootstrap-primary] %s\n' "$*" >&2; }

step1_prereqs() {
  log "step 1/6: checking prerequisites"
  command -v docker >/dev/null || { log "docker not found — install first"; exit 1; }
  docker compose version >/dev/null || { log "docker compose v2 not found"; exit 1; }
  command -v git >/dev/null || { log "git not found"; exit 1; }
  command -v openssl >/dev/null || { log "openssl not found"; exit 1; }
  command -v curl >/dev/null || { log "curl not found"; exit 1; }
  [[ -f "$REPO_DIR/docker-compose.peer.yml" ]] || {
    log "docker-compose.peer.yml not found in $REPO_DIR — wrong CWD?"; exit 1
  }
}

step2_keyfile() {
  log "step 2/6: ensuring Mongo keyfile"
  mkdir -p "$REPO_DIR/secrets"
  if [[ ! -s "$REPO_DIR/secrets/mongo-keyfile" ]]; then
    openssl rand -base64 756 > "$REPO_DIR/secrets/mongo-keyfile"
    chmod 400 "$REPO_DIR/secrets/mongo-keyfile"
    sudo chown 999:999 "$REPO_DIR/secrets/mongo-keyfile"
    log "  generated new keyfile"
  else
    log "  already present"
  fi
}

step3_env() {
  log "step 3/6: writing .env"
  if [[ -f "$REPO_DIR/.env" ]]; then
    log "  .env exists — leaving untouched (delete to re-generate)"
    return
  fi
  local mongo_pw
  mongo_pw="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  cat > "$REPO_DIR/.env" <<EOF
# Generated by bootstrap-primary.sh on $(date -Iseconds)
MONGO_USER=mcp_orch
MONGO_PASSWORD=$mongo_pw
MONGO_DB=mcp_orchestrator

ORIGIN_SERVER_ID=$ORIGIN_SERVER_ID

# sync-engine vars: not used (sync-engine isn't started on the test-primary).
# Set to placeholders so docker-compose env parsing doesn't fail if anyone
# ever runs \`docker compose -f docker-compose.peer.yml up sync-engine\` here.
JUNTO_SYNC_PRIMARY_URL=http://placeholder/mcp
JUNTO_SYNC_PRIMARY_KEY=placeholder
JUNTO_SYNC_LOCAL_KEY=placeholder
EOF
  chmod 600 "$REPO_DIR/.env"
  log "  wrote $REPO_DIR/.env (mode 600)"
}

step4_compose_up() {
  log "step 4/7: bringing up chromadb + mongodb + mcp-server"
  cd "$REPO_DIR"
  docker compose -f docker-compose.peer.yml up -d --build chromadb mongodb mcp-server
}

# Idempotently initiate the rs0 single-node replica set. The mongo:7.0 image
# starts the daemon with --replSet rs0 but does NOT run rs.initiate(); without
# it there's no primary and every write fails with "No primary exists currently"
# even though docker's healthcheck (which uses directConnection=true to bypass
# replica-set discovery) reports healthy. Sage's prod deployment was initiated
# manually in the distant past and the data volume preserves rs0 config — so
# this gap only surfaces on truly fresh installs (this script, peer-deployment.md
# adopters, anyone restoring without a mongo-data backup).
step5_initiate_rs() {
  log "step 5/7: ensuring rs0 replica set is initiated"
  # shellcheck disable=SC1091
  set -a; source "$REPO_DIR/.env"; set +a
  local primary_host="${MONGO_RS_HOST:-mongodb}"
  local n=0
  until docker exec junto-peer-mongodb mongosh --quiet --norc \
    "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/?directConnection=true&authSource=admin" \
    --eval "
      try {
        const s = rs.status();
        if (s.ok && s.members && s.members.some(m => m.stateStr === 'PRIMARY')) {
          print('rs0 already initialized with primary');
          quit(0);
        }
      } catch (e) {
        if (e.codeName !== 'NotYetInitialized' && e.code !== 94) {
          print('rs.status failed: ' + e.message);
          quit(1);
        }
        const r = rs.initiate({_id: 'rs0', members: [{_id: 0, host: '${primary_host}:27017'}]});
        if (!r.ok) { print('rs.initiate failed: ' + JSON.stringify(r)); quit(1); }
        print('rs0 initiated');
      }
      // wait up to 30s for primary election
      for (let i = 0; i < 30; i++) {
        try {
          if (db.hello().isWritablePrimary) { print('primary elected after ' + i + 's'); quit(0); }
        } catch (e) {}
        sleep(1000);
      }
      print('primary never elected'); quit(1);
    " >/dev/null 2>&1; do
    n=$((n+1))
    if (( n > 12 )); then
      log "  rs.initiate never succeeded — check 'docker logs junto-peer-mongodb'"
      exit 1
    fi
    sleep 5
  done
  log "  rs0 ready"
}

step6_wait_health() {
  log "step 6/7: waiting for /health"
  local n=0
  until curl -fsS http://localhost:8080/health >/dev/null 2>&1; do
    n=$((n+1))
    if (( n > 60 )); then
      log "  /health never came up — check 'docker logs junto-peer-mcp-server'"
      exit 1
    fi
    sleep 2
  done
  log "  /health OK after ~$((n*2))s"
}

step7_issue_key() {
  log "step 7/7: issuing admin API key for peer to use"
  # Idempotency guard: if peer-credentials.txt exists, the operator has the
  # raw key from a prior run. Creating a same-named key would hit the
  # api_keys.name unique index; the raw value can't be recovered from Mongo
  # (only the hash is stored). Leave the existing file untouched.
  if [[ -s "$CREDS_OUT" ]] && grep -q '^JUNTO_SYNC_PRIMARY_KEY=' "$CREDS_OUT"; then
    log "  $CREDS_OUT already present with a key — leaving untouched."
    log "  Delete $CREDS_OUT (and revoke the old key in mongo) to regenerate."
    return
  fi
  local raw
  raw="$(docker exec junto-peer-mcp-server python -c "
from shared_memory.auth import create_api_key
raw, _ = create_api_key(name='$PRIMARY_KEY_NAME', role='admin', created_by='bootstrap-primary.sh')
print(raw)
")"
  [[ -n "$raw" ]] || { log "  key creation returned empty — investigate"; exit 1; }

  local primary_ip
  primary_ip="$(ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | head -1)"

  cat > "$CREDS_OUT" <<EOF
# Generated by bootstrap-primary.sh on $(date -Iseconds)
# Hand these to bootstrap-peer.sh on VM2.
#
# After Tailscale is up on this VM, replace JUNTO_SYNC_PRIMARY_URL's host
# with this VM's tailnet name/IP (e.g., http://primary.<tailnet>.ts.net:8080/mcp).
JUNTO_SYNC_PRIMARY_URL=http://$primary_ip:8080/mcp
JUNTO_SYNC_PRIMARY_KEY=$raw
ORIGIN_SERVER_ID_REMOTE=$ORIGIN_SERVER_ID
EOF
  chmod 600 "$CREDS_OUT"
  log "  wrote $CREDS_OUT (mode 600)"
  log ""
  log "DONE. Hand $CREDS_OUT to VM2 (peer)."
  log "Current LAN IP: $primary_ip"
  log "Once Tailscale is up, swap the host in JUNTO_SYNC_PRIMARY_URL for the tailnet address."
}

step1_prereqs
step2_keyfile
step3_env
step4_compose_up
step5_initiate_rs
step6_wait_health
step7_issue_key
